### ISSUE TITLE
Support for variable fonts

### ISSUE THREAD

**Issue by janwirth** [seek-oss/capsize#101]
Is it possible or planned? :)

**Comment by michaeltaranto** [comment]
Hey 👋 , i have not looked into variable fonts in terms of the impact it could have on the font metric-based trims. Would be something to have a look at at some stage.

Do you have any info? Is it currently working? Partially working? Not at all?

**Comment by janwirth** [comment]
Sorry for the imprecise report. Right now the controls are missing. It does detect the metrics for the default size correctly.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/7485959/201294575-0a9041fa-e13c-48fc-8490-5452517a6098.png">

Here is the variable font I used. It's practically the new _Inter_. :)

[pretendard.zip](https://github.com/seek-oss/capsize/files/9988148/pretendard.zip)

**Comment by michaeltaranto** [comment]
Ah yep, I built the controls in the UI to help identify metrics visually (as well as refine missing metrics), so not expecting buttons to appear automatically based on the font.

Did you have some example font settings you have used with this font that would affect the capheight or baseline?

**Comment by janwirth** [comment]
Actually, the variable font is not affected by the font-weight change. Below screenshots of 100 & 900 font-weights with the same capsize style object.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/7485959/202300193-4d44ef05-6190-48bc-874d-80c568f8c33a.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/7485959/202300483-d9c4f47f-1291-478e-b190-18b214c0a7d6.png">

Thank you for your amazing work! You may close this issue.

**Comment by janwirth** [comment]
Here's the environment for testing it: https://stackblitz.com/edit/typescript-xfd2yg?file=index.ts,style.css
