### ISSUE TITLE
Text-overflow: ellipsis is not working

### ISSUE THREAD

**Issue by janwirth** [seek-oss/capsize#116]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/7485959/203285022-b28a20c4-5579-49b4-988b-2f4f41abde63.png">

When I remove the pseudo-elements it works. Perhaps a single-line-mode that uses margins instead of pseudo elements is the fix?

**Comment by michaeltaranto** [comment]
Yes while the trim technique tries its best to not interfere with other styles there are certain techniques that are simply not possible to apply to the same node — text overflow is one of them.

The best work around for this is to nest [apply the truncation styles to a span element] within the element being trimmed.

Hope that helps.

[apply the truncation styles to a span element]: https://github.com/seek-oss/capsize/issues/15#issuecomment-663279448

**Comment by janwirth** [comment]
Thank you :)
