### ISSUE TITLE
Latest version of `@capsizecss/metrics` doesn't generate font files

### ISSUE THREAD

**Issue by gpahal** [seek-oss/capsize#131]
I installed the latest version of `@capsizecss/metrics@1.1.0` and tried to run the example code from the README:

```ts
import { createStyleObject } from '@capsizecss/core';
import arialMetrics from '@capsizecss/metrics/arial';

const capsizeStyles = createStyleObject({
  fontSize: 16,
  leading: 24,
  fontMetrics: arialMetrics,
});
```

I got an error saying that `@capsizecss/metrics/arial` module was not found. This works perfectly in v1.0.1

**Comment by michaeltaranto** [comment]
Thanks for reporting. Let me check it out and get back to you

**Comment by michaeltaranto** [comment]
Yes something has definitely broken. The latest version added new entrypoints for other functionality, but seems to have stopped publishing the built metric files.

I would recommend staying on `v1.0.1` for now and we'll look to get a fix out.

**Comment by michaeltaranto** [comment]
Closed by https://github.com/seek-oss/capsize/pull/133

**Comment by gpahal** [comment]
Thanks for the quick fix!
