### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by nusr** [seek-oss/capsize#140]
steps to reproduce
1. git clone https://github.com/seek-oss/capsize.git
2. pnpm i
3. pnpm start

MacOS 13.3.1
node version: 16.20.0
npm version: 8.19.4
pnpm version: 7.29.1

error log:
```
> capsize@0.0.0 start
> pnpm site:start


> capsize@0.0.0 site:start /Users/bytedance/github/capsize
> manypkg run site start

yarn run v1.22.11
$ gatsby develop -H 0.0.0.0
success open and validate gatsby-configs - 0.124s
success load plugins - 0.611s
success onPreInit - 0.027s
success initialize cache - 0.006s
success copy gatsby files - 0.107s
success onPreBootstrap - 0.019s
success createSchemaCustomization - 0.005s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.061s
success building schema - 0.202s
info Total nodes: 37, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.007s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.056s
success update schema - 0.017s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.444s
success onPostBootstrap - 0.447s
info bootstrap finished - 4.414s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.300s
success write out requires - 0.004s
success run page queries - 0.015s - 1/1 65.70/s
warn Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@capsizecss/metrics/abrilFatface' in '/Users/bytedance/github/capsize/site/src/components'

If you're trying to use a package make sure that '@capsizecss/metrics/abrilFatface' is installed. If you're trying to use a
local file make sure that the path is correct.

File: src/components/SiteProvider.tsx


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@capsizecss/metrics/roboto' in '/Users/bytedance/github/capsize/site/src/components'

If you're trying to use a package make sure that '@capsizecss/metrics/roboto' is installed. If you're trying to use a local
file make sure that the path is correct.

File: src/components/SiteProvider.tsx


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '@capsizecss/metrics/roboto' in '/Users/bytedance/github/capsize/site/src/components'

If you're trying to use a package make sure that '@capsizecss/metrics/roboto' is installed. If you're trying to use a local
file make sure that the path is correct.

File: src/components/AppStateContext.tsx

failed Building development bundle - 7.842s
```

**Comment by michaeltaranto** [comment]
Have had a quick look at this, the site is not in a good state and need of an upgrade to demo the full power of what Capsize has grown to solve more broadly.

As most dont run the site locally, I have published [a guide for running the site on M1 Macs] as that was an issue in the past.

I just tried to run the site now (first time since upgrading to MacOS 13, and got a different error:
```
error:0308010C:digital envelope routines::unsupported
```
which after some googling, led me to this [answer](https://stackoverflow.com/a/69699772).

So running the following worked for me:
```
NODE_OPTIONS=--openssl-legacy-provider pnpm start
```

[a guide for running the site on M1 Macs]: https://github.com/seek-oss/capsize/blob/master/site/running-site-locally.md

**Comment by nusr** [comment]
> NODE_OPTIONS=--openssl-legacy-provider pnpm start



> Have had a quick look at this, the site is not in a good state and need of an upgrade to demo the full power of what Capsize has grown to solve more broadly.
> 
> As most dont run the site locally, I have published [a guide for running the site on M1 Macs](https://github.com/seek-oss/capsize/blob/master/site/running-site-locally.md) as that was an issue in the past.
> 
> I just tried to run the site now (first time since upgrading to MacOS 13, and got a different error:
> 
> ```
> error:0308010C:digital envelope routines::unsupported
> ```
> 
> which after some googling, led me to this [answer](https://stackoverflow.com/a/69699772).
> 
> So running the following worked for me:
> 
> ```
> NODE_OPTIONS=--openssl-legacy-provider pnpm start
> ```

The following command fixes this problem

```
pnpm run metrics:build && NODE_OPTIONS=--openssl-legacy-provider pnpm start
```
