### ISSUE TITLE
Getting an error when using createTextStyle

### ISSUE THREAD

**Issue by DianaGordonLemonade** [seek-oss/capsize#145]
I'm working on a monorepo, based on nx, and using vite, vitest, vanilla-extract, react and typescript.
I use `createTextStyle` within my Typography component like this:
`export const textCapsize = createTextStyle({
  fontSize: 14,
  leading: 20,
  fontMetrics: ourFontMetrics,
});`

(ourFontMetrics is imported from `'@capsizecss/metrics'`)
I use textCapsize within our recipe (vanilla-extract).

I'm getting a test failure with the following error:
Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:
       
       - You may have created styles outside of a '.css.ts' context
       - You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started`

It looks like something is missing from our configuration but wasn't able to find it.

**Comment by michaeltaranto** [comment]
Hey Diana, sounds like there is a bit going on in terms of tooling so its hard to say where it could be breaking without having a repro. Do you have something you can share?

**Comment by michaeltaranto** [comment]
We have just released an uplift to all Capsize packages that changes the way we package and build our entry points. Across the board we should have better types and ESM support. There was also a bug with the Vanilla Extract integration in ESM where styles could go missing ([see release notes for v2]).

Feel free to reopen with a repro if things are still not as expected.

[See release notes for v2]: https://github.com/seek-oss/capsize/blob/master/packages/vanilla-extract/CHANGELOG.md#200
