### ISSUE TITLE
capsize_capsizeStyle rules not being built in Remix projects

### ISSUE THREAD

**Issue by joryphillips** [seek-oss/capsize#146]
It looks like @capsizecss/vanilla-extract is not including the `capsize_capsizeStyle` rules (or related pseudo elements) when in a Remix project.  The element in question has the correct className included, but the styles themselves are missing.

Here is a quick screenshot that shows the problem:
![image](https://github.com/seek-oss/capsize/assets/7508307/354c3476-d17e-4491-8e50-2f38e880da1b)

In the above image you can see that `capsize_capsizeStyle_1d0g9qk4` is one of the included class names, but its rules are missing.

Here is a [minimal reproduction in stackblitz](https://stackblitz.com/edit/remix-run-remix-pz3ngp?file=app%2Fcomponents%2Ftext%2FText.tsx,app%2Fcomponents%2Ftext%2FText.css.ts)

Let me know if I can provide any more info or troubleshooting help, or if I am doing something wrong.

**Comment by joryphillips** [comment]
Update: I was able to fix locally by changing `return composeStyles(capsizeStyle, style(vars, debugId));` to `return style([capsizeStyle, style(vars, debugId)]);`

**Comment by michaeltaranto** [comment]
Sorry, i missed your follow up comment here.

Wanted to hold off on the requirement for consumers to bump the peerDep originally, but enough time has passed now.

I'll get an update out.

**Comment by michaeltaranto** [comment]
@joryphillips if you have time, I have published a snapshot that would be great to have you validate.

`@capsizecss/vanilla-extract@0.0.0-upgrade-vanilla-extract-20231114045600`

**Comment by michaeltaranto** [comment]
Closing this as we have updated our VE peer dep. Feel free to open again if you dont believe this is resolved.
