### ISSUE TITLE
Cuts off descenders when using common CSS approaches for line truncation

### ISSUE THREAD

**Issue by camdub** [seek-oss/capsize#15]
The two most common approaches I've seen for line truncation are summarized in this [CSS Tricks article](https://css-tricks.com/almanac/properties/l/line-clamp/). Using either approach causes the descenders to be hidden.

![CleanShot 2020-07-23 at 17 49 07](https://user-images.githubusercontent.com/503674/88342166-e98f3680-cd0c-11ea-96ce-9d3210239390.png)

The screenshot above was captured after adding the following styles to the `div` that wraps the text on https://seek-oss.github.io/capsize/. The font in the screenshot is Roboto from Google Fonts.

```
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;
```

Would the best way forward for me to support truncation be to look at using a JS approach like Clamp.js?

**Comment by michaeltaranto** [comment]
Hey 👋 

There are trade offs to not having native support for this trim, and being mindful of how overflow is handled is one of them. Ideally you don't add further layout-related styles to the node that is capsized. For truncation we use the following technique:

```html
<style>
.truncate {
  display: block;
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
</style>

<div class="capsizedText">
  <span class="truncate">...</span>
</div>
```

**Comment by camdub** [comment]
Great, thanks!
