### ISSUE TITLE
Not finding capsize properly for this font

### ISSUE THREAD

**Issue by maraisr** [seek-oss/capsize#2]
**WARNING** I do recognize that this isnt released yet, and Im by no means using in production. Just a mere fellow dev giving it a whirl, because im excited.

Our custom bought font we use in our design system doesn't seem to work. Just wanting to let you guys know in case there is a bug.

Font: https://cdn.autoguru.com.au/assets/fonts/avertastd-regular-webfont.woff2 (there is a woff too)

<img width="1207" alt="Screen Shot 2020-06-04 at 5 12 14 pm" src="https://user-images.githubusercontent.com/599459/83726372-ca6a1600-a686-11ea-8d20-2e6ff8376d93.png">

---
Also; the website doesnt work in firefox :/

Once again. Please see this as a friendly fyi, nothing more, nothing less. Close the issue if you feel   :)

**Comment by michaeltaranto** [comment]
Thanks for the super super early feedback haha. It's finding using the cap height from inside the font file itself and drawing that correctly. However i have come across a handful of fonts like this, need more R&D into possible work arounds.

**Comment by brent-williams** [comment]
Ditto on one of my fonts.  But website allows manual editing of capsize w/ immediate feedback so narrowing it down to the correct value is doable manually at least.  Great work guys keep it going!

<img width="1004" alt="Screen Shot 2021-11-16 at 1 39 14 pm" src="https://user-images.githubusercontent.com/1694687/141891732-c720fc91-3ce6-430b-9fd9-f7b252f0d212.png">

**Comment by michaeltaranto** [comment]
> Ditto on one of my fonts. But website allows manual editing of capsize w/ immediate feedback so narrowing it down to the correct value is doable manually at least. Great work guys keep it going!
> 
> <img alt="Screen Shot 2021-11-16 at 1 39 14 pm" width="1004" src="https://user-images.githubusercontent.com/1694687/141891732-c720fc91-3ce6-430b-9fd9-f7b252f0d212.png">

@brent-williams thanks for taking the time to share this. Unfortunately for capsize it relies on the meta data provided inside the font by its author. Most of the time this is correct, but in these cases your only option is to update it manually.
