### ISSUE TITLE
Horriable error in build and dev command nuxt 3

### ISSUE THREAD

**Issue by pegahka29** [seek-oss/capsize#204]
when I want  to run 'pnpm dev' , the below error happens ! what's that?
Cannot start nuxt:  EMFILE: too many open files, open 'D:\Projects\DIBA_PWA\node_modules\@capsizecss\metrics\hennyPenny.d.ts

I installed all versions of this package but error is exist

**Comment by michaeltaranto** [comment]
Thanks for reaching out. From the details above, it is difficult to identify a possible cause. If you can demonstrate how your using the libraries and versions of the environment it may be helpful. Alternatively a reproduction repo?
