### ISSUE TITLE
`text-box-trim` and `text-box-edge` in Canary behind a flag 

### ISSUE THREAD

**Issue by argyleink** [seek-oss/capsize#205]
```css
h1 {
  text-box-trim: both;
  text-box-edge: ex alphabetic;
```

<img width="787" alt="Screenshot 2024-06-10 at 1 35 14 PM" src="https://github.com/KyleAMathews/vite-plugin-capsize-radix-ui/assets/1134620/527653f7-9d78-458c-938c-4696cd3fd132">

Would love to capture feedback from experiments you do. [Spec for ref](https://drafts.csswg.org/css-inline-3/#leading-trim).

**Comment by michaeltaranto** [comment]
Thanks for sharing, i'll try and summarise some thoughts:

### `text-box-edge`
I find this property a little unpredictable. Setting the edge to `cap` or `ex` and not using the `alphabetic` baseline seems counter intuitive i feel, as both metrics are measured from this point.

My opinion would be that both `cap` and `ex` set the bottom edge to alphabetic baseline by default.

Note: The image below (used in [Section 5.2 / Figure 5]) I think would be more valuable if it used a font that had greater difference between the cap height and the ascender. This would help to illustrate the distinct edge values.

<img src="https://github.com/seek-oss/capsize/assets/912060/6b92c16e-d4bc-4c22-b2c1-2bb60c119927" alt="Three different values of the text-box-edge property." width="60%" />

[Section 5.2 / Figure 5]: https://drafts.csswg.org/css-inline-3/#text-edges

---

So in the future the trim that Capsize provides could be:

```css
.text {
  text-box-edge: cap; // (assuming above feedback, means not requiring `alphabetic`)
  text-box-trim: both;
}
```

Let me know if you want to talk further about the above.

**Comment by argyleink** [comment]
great items of feedback! I've sent a summarization to the eng team as well as a link to this post. will post back here with any changes made due to the feedback, thanks! 🙏🏻
