### ISSUE TITLE
Font `Nunito Sans` not supported

### ISSUE THREAD

**Issue by matteofrana** [seek-oss/capsize#212]
It seems the font `Nunito Sans` is still not supported.
This causes an error "Failed to find font override values for font Nunito Sans" in Next.js, unless the font is imported with `adjustFontFallback: false`.

Is there any plan to support Nunito Sans soon?
Thanks, Matteo

**Comment by michaeltaranto** [comment]
Hey Matteo, the Nunito Sans font is supported in Capsize metrics (see [here]). There may be an issue upstream in the Next ecosystem that needs debugging.

If you do find something we've missed feel free to reopen this.

[here]: https://unpkg.com/browse/@capsizecss/metrics@3.2.0/entireMetricsCollection/nunitoSans/
