### ISSUE TITLE
Reverse margin direction for :before and :after to prevent margin-collapse?

### ISSUE THREAD

**Issue by miragecraft** [seek-oss/capsize#26]
Just wondering what is the rationale to use margin-top for :before and margin-bottom for :after instead of the other way around.

Seems to me if you reverse margin direction you avoid having to define padding: 0.05px 0; to prevent margin collapse.

**Comment by michaeltaranto** [comment]
Hey 👋 

Thanks for the suggestion, you had me for a minute there thinking I had overlooked a much simpler alternative! But unfortunately the approach you described does not work as intended — it trims the height of the text node, but the visual space is still left above and below the node from a container perspective.

Here is [a demo of the margin collapse guard working in Playroom](https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8UCWA3ABAZwC4E8AbGAXmGEwAcBDKNAOwHN5MAmABgBpMBbagDwDqqKLgAWLACzsuvagCdGqeiwA6IdpmoBXXBHWYAvoYB8q%2BpkxJKOAsTIVIhCPLUg0PRvOr4DxsxaWmADC1JTYqABeMJh6UD6YABQA7qjicorKmE6EYdgxjNoKUACU5pZIAPSUAeVWaOh1lnhEpOSYAEbUYADWXhDa9FBu8jBQ6txiMKiMYrgsAIzclBARuKgQKpjqo7nr6DATmJEAkkMw-ItGhnWVtYFI%2BWDrm7atDp3dffIDQ24AsmNUNoeAAVbTyACO2ggqHyflMTXqGDe9naADNNrgAMpRGBuBYAVnYlH4RxodGUzG2GgAdOxCaSEQEgkEUCiWmiKHxMvRQRBKG4ALTsWmsSQwHgIzB3JGWAASMEIzjlyKwnLa3IUSnoACEILg9DxhaLWISJVKQNcZSy2ZUGraqk8XvR7hUGkiNR8ur1%2BoNhjTRuMQJNprN5pgllRVmkNlsdkrqPtDiHjmdYJdI9dbm6rB15Da6kh84X6EWbF72k4XG4PF4fMykaFwnjMKlxANcBkddkIMq8gUivIoJgAGSYZQHeS4MaYegwRhJjAxHk9tCjZ5xovVXPFguyh4lg8VI%2B7j2BZp2TWfX0-f0jMZHKYzOaLZYxl0PvbLo6nc6ZhZs0CA8i2dONUWvH1vl%2BAN1EBNAQXBKEYThFNrltd0OSvD5MXoHE8QJYkmStfxVXZdVsPaVdlH1Q0IGNGkRTFC1pWPVlMEVZV9AvNkGggj5qL5AUTTFc1JVYjCrHtDBHUqMDNjPDBPUoigoL9P5A0fVNn3DN9ozWOMvyXA5f3TC4rmMHNzCLU8bP3R1bLLB4KxU3tnFcGk628XwSMRHiAEFsEwfABmyagLHyGJxBibAaDAGI4VieRUB4HhZ2maKCwiWBMAgdFYimWILi7SA8OoZQYHkbgOl0JFopvaD-TcgYC1gHhNjwbwZyC8QkwKldtSyRKcjyKlcrwiB%2BqRGhRjw3syoq%2BRaW3GpzCqB1zBDEBorS7AEAAbRAMJuhAABdTgQFSUQxD2%2BB9oAdgANgADlOwwgA).

**Comment by miragecraft** [comment]
[I found the cause](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) - empty elements will have their top and bottom margin collapse, which is what happened here with the :before and :after elements.

It didn't matter that the margin direction were reversed, they collapsed within themselves first and then was able to collapse with parent's margin.

Sorry for the false alarm.

**Comment by miragecraft** [comment]
Just discovered something, instead of setting the :before and :after to display: block, setting them to flex or table (wider browser support) will allow you to drop the margin collapse guard.

This needs to be combined with reversed margin direction suggested earlier (that didn't work by themselves).

**Comment by michaeltaranto** [comment]
Hey now that's interesting! I remember coming across table having special powers to prevent collapse but forgot about it here. What's interesting too is we can also drop the `height: 0` on the pseudo elements — that was required to prevent the collapsing of an empty block element, but seemingly not for a table.

So far this is looking promising.

```diff
{
  "fontSize": "",
  "lineHeight": "",
- "padding": "0.05px 0",
  "::before": {
    "content": "''",
    "marginBottom": "",
+   "display": "table"
-   "display": "block",
-   "height: 0"
  },
  "::after": {
    "content": "''",
    "marginTop": "",
+   "display": "table"
-   "display": "block",
-   "height: 0"
  }
}
```

**Comment by phloe** [comment]
As a sidenote the CSS custom props based text-crop I have been working on uses flipped margins - but with padding moved to the pseudos to prevent collapse :)

https://jsfiddle.net/phloe/yrg3L8to/

But just using `display: table;` is much cleaner :)

**Comment by adamduncan** [comment]
I was digging into a similar alternative to prevent collapsing margins and the need for padding elements.

Josh Comeau has a great post on margin collapsing. It sparked a thought: Could one use `display: flow-root` on the text element. That would also nicely negate the need for factoring padding into the calculation:

https://www.joshwcomeau.com/css/rules-of-margin-collapse/ (under "Margin-blocked")

**Comment by phloe** [comment]
Yeah - much cleaner. iOS only supports it from 13 and up though.

**Comment by pdimova** [comment]
> I was digging into a similar alternative to prevent collapsing margins and the need for padding elements.
> 
> Josh Comeau has a great post on margin collapsing. It sparked a thought: Could one use `display: flow-root` on the text element? That would also nicely negate the need for factoring padding into the calculation:
> 
> https://www.joshwcomeau.com/css/rules-of-margin-collapse/ (under "Margin-blocked")

This is it! 

In our case, we had a misalignment issue displaying cropped link text inside a paragraph, so changing the pseudo-elements display values to `flow-root` instead of `table` solve it.

**Comment by michaeltaranto** [comment]
@pdimova would you mind sharing a before and after? A codepen or codesandbox that shows the issue would be great.

Unfortunately a solution that is >=iOS 13 is not usable for us, but keen to see the problem you're facing.

**Comment by Vanals** [comment]
Hi @michaeltaranto ! I work with @pdimova  and trying to solve with her our issue.

This is a code pen with our scenario:
https://codepen.io/pollx/pen/mdBJZoq

Seems like that using `display: flow-root` rather than `display: table`,  in the .flex-child ::before and ::after, could solve our issue. Would be great if you could share your thoughts on this!

I am aware the HTML structure is not the cleanest one, but this is how it is atm :D. 

Thank you.

**Comment by pdimova** [comment]
> @pdimova would you mind sharing a before and after? A codepen or codesandbox that shows the issue would be great.
> 
> Unfortunately a solution that is >=iOS 13 is not usable for us, but keen to see the problem you're facing.

hey @michaeltaranto! Thank you for your reply! 

I see my colleague has already shared a codepen example with you :)

Could you please elaborate more on this line here?
> Unfortunately a solution that is >=iOS 13 is not usable for us, but keen to see the problem you're facing.
