### ISSUE TITLE
Production suitability?

### ISSUE THREAD

**Issue by encho** [seek-oss/capsize#27]
Hello,

first of all thanks for this great library!

I am considering introducing this approach on my job! I have come across this post where potential cross browser issues are mentioned: https://uxdesign.cc/the-4px-baseline-grid-89485012dea6

Did you stumble upon such issues using this approach in production?

Many thanks

**Comment by michaeltaranto** [comment]
Hey 👋  

Like anything you pull into your app you need to understand the trade offs. We are running this in production on our sites. There are trade offs around fallback fonts (checkout the [FAQs](https://seek-oss.github.io/capsize/#faq)) and system font stacks.

I would suggest trying to use it and test your app with each font in your font stack and make the call if it suits your use case.

**Comment by encho** [comment]
Hi Michael, thanks for the response. I will test the implementation on different Browsers and with different fonts in my stack then.
