### ISSUE TITLE
createStyles utility

### ISSUE THREAD

**Issue by souporserious** [seek-oss/capsize#28]
First, thanks for such a great little utility library!

I was curious if you'd be willing to add a `createStyles` utility that would allow exporting just the calculated styles so this library can be used more easily in React Native? I've tested it out and it seems to work great! Just a little awkward having to pull the styles off and rework them. Happy to help put a PR together if this sounds good, just let me know :)

**Comment by michaeltaranto** [comment]
Hey 👋 

Yeah interested in this, i did some early exploration on the technique in Snack and it looked promising. Just never progressed it as we dont have the use case.

There is a little ecosystem evolving around capsize which is cool to test out different languages/tools etc. Have you seen [react-native-capsize](https://www.npmjs.com/package/react-native-capsize)? Be keen to hear your thoughts on it. If the implementation is sound and works well cross platform we could look to fold it in down the track.

**Comment by souporserious** [comment]
Oh, nice! I haven't seen that, but it looks like exactly what I need, thanks! Feel free to close this, still happy to start a PR when I get a chance if you want.
