### ISSUE TITLE
ESM incompatibility due to round-to (direct dependency)

### ISSUE THREAD

**Issue by sync** [seek-oss/capsize#30]
First of all thank you for providing and esm export but unfortunately it's not working as expected because round-to (a direct dependency) isn't an esm module itself.

Error:

```
SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.
```

See reproduction here (capsize):
https://esm.codes/#aW1wb3J0IGNhcHNpemUgZnJvbSAnaHR0cHM6Ly91bnBrZy5jb20vY2Fwc2l6ZSc7Cgpjb25zdCBzdHlsZXMgPSBjYXBzaXplKHsKICBjYXBIZWlnaHQ6IDE2LAogIGxpbmVHYXA6IDgsCiAgZm9udE1ldHJpY3M6IHsKICAgIGNhcEhlaWdodDogNzAwLAogICAgYXNjZW50OiAxMDU4LAogICAgZGVzY2VudDogLTI5MSwKICAgIGxpbmVHYXA6IDAsCiAgICB1bml0c1BlckVtOiAxMDAwLAogIH0sCn0pOwoKY29uc29sZS5sb2coInN0eWxlczogIiwgc3R5bGVzKTs=

or 

```
import capsize from 'https://unpkg.com/capsize';

const styles = capsize({
  capHeight: 16,
  lineGap: 8,
  fontMetrics: {
    capHeight: 700,
    ascent: 1058,
    descent: -291,
    lineGap: 0,
    unitsPerEm: 1000,
  },
});

console.log("styles: ", styles);
```

See reproduction here (round-to):
https://esm.codes/#aW1wb3J0IHJvdW5kVG8gZnJvbSAnaHR0cHM6Ly91bnBrZy5jb20vcm91bmQtdG8nOwoKY29uc29sZS5sb2coInJvdW5kOiAiLCByb3VuZFRvKDEuMjM0LCAyKSk7

or 

```
import roundTo from 'https://unpkg.com/round-to';

console.log("round: ", roundTo(1.234, 2));
```

Be careful not to use a cdn like `cdn.skypack.dev` it will look like it's working because they magically translate non esm module into esm module on the fly, see here:
 
https://esm.codes/#aW1wb3J0IHJvdW5kVG8gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvcm91bmQtdG8nOwoKY29uc29sZS5sb2coInJvdW5kOiAiLCByb3VuZFRvKDEuMjM0LCAyKSk7
 
or

```
import roundTo from 'https://cdn.skypack.dev/round-to';

console.log("round: ", roundTo(1.234, 2));
```

**Comment by ShayDavidson** [comment]
We have the same issue and we can't use capsize in production because of that.

**Comment by michaeltaranto** [comment]
Will be removing the dependency in favour of internalising the function as part of an upcoming PR.

**Comment by michaeltaranto** [comment]
Resolved by #33

**Comment by sync** [comment]
let me know if there is a pre release somewhere so I can try it if not it's fine I'll wait for the next release

**Comment by michaeltaranto** [comment]
Finally merged this and Github Actions is [having issues](https://www.githubstatus.com/incidents/s654n76c1bwr) 🤦

**Comment by michaeltaranto** [comment]
@sync hmm, might need a bit more work here. I have removed the `round-to` dependency and capsize has a default export. Any ideas i what im doing wrong?

**Comment by michaeltaranto** [comment]
Hopefully the move from [Preconstruct] to [Crackle] ([in v4]) should have fixed the issues experienced with ESM entrypoints.

[Preconstruct]: https://preconstruct.tools/
[Crackle]: https://github.com/seek-oss/crackle?tab=readme-ov-file#-crackle-
[in v4]: https://github.com/seek-oss/capsize/releases/tag/%40capsizecss%2Fcore%404.0.0
