### ISSUE TITLE
Document that it's the hhea ascender/descender/lineGap that matter.

### ISSUE THREAD

**Issue by dabrahams** [seek-oss/capsize#59]
https://codepen.io/dabrahams/pen/BadXbRe shows a port of the capsize computations to scss; I've verified they give the same numerical results as the typescript code for 3 different fonts.  

As you can see, the tops of the paragraphs are all offset downward, whereas I expected to see the top of the first paragraph at 0.  At the top of the SCSS you can switch the font size arbitrarily, and set the font to either `'arial'` or  `'georgia'` (or any other font you like, as long as you add the metrics around line 119 of the SCSS).

Am I doing something wrong here?  Missing something?

Many thanks in advance.

**Comment by dabrahams** [comment]
Actually I *think* this was due to me using the font's ascender, descender, and line gap values rather than its **hhea** ascender, hhea descender, and hhea line gap!  The documentation should really be clear about which to use.

I'm not certain I entirely like the results I'm getting using the capsize formulas; will follow up with my own for comparison.

**Comment by dabrahams** [comment]
Yeah, the results I get using my own formulas match capsize, now that I am feeding it the right metric values.

**Comment by dabrahams** [comment]
Sorry about the close.  Reopening to deal with the documentation issue.

**Comment by michaeltaranto** [comment]
Thanks for digging into this. Glad you're finding the technique useful.

I am wanting to do a documentation and site uplift but just haven't had time to do it. I would suggest that documenting the internal metrics tables is not really something the Capsize documentation would do. Capsize deliberately tries to abstract that detail away where possible.

I based a lot of my work on this fantastic post: [Deep dive CSS: font metrics, line-height and vertical-align](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align) by [Vincent De Oliveira](https://twitter.com/iamvdo). This really helps identify which parts of the metrics the browse cares about when rendering.

Hope that helps.

**Comment by dabrahams** [comment]
>  I would suggest that documenting the internal metrics tables is not really something the Capsize documentation would do. Capsize deliberately tries to abstract that detail away where possible.

It also exposes APIs that take ascent, descent, and lineGap parameters.  If I am trying to use this API, I'm going to dig up those values. If you open a font with [FontLab](https://www.fontlab.com) you will find values with those labels prominently available in the "family dimensions" pane
<img width="826" alt="image" src="https://user-images.githubusercontent.com/44065/144141688-288c50f9-c466-4bdd-a263-22451ba38c7b.png">
when the ones you actually want for use with capsize are buried in "other values":
<img width="826" alt="image" src="https://user-images.githubusercontent.com/44065/144141766-c6f06a17-cc5f-4d79-b85d-4f6501b3d271.png">

This just seems like a recipe for failure of other users.  I had actually read the article by Mr. De Olivera and when I didn't see hhea in the metrics displayed by FontLab, I assumed that the software omitted that particular label.  It was only on my 3rd re-reading of the article that it occurred to me to dig further to find the relevant values.

**Comment by michaeltaranto** [comment]
Yep agreed, from a Capsize perspective, the documentation failure is not about which tables to look at, rather how to use the suite of capsize packages to extract these values (without needing FontLab).
- The [@capsizecss/unpack](https://github.com/seek-oss/capsize/tree/master/packages/unpack) package does this for you and will extract the metrics from the font given a url or a file.
- The [@capsizecss/metrics](https://github.com/seek-oss/capsize/tree/master/packages/metrics) package does this for you and provides you with system metrics as well as google fonts, directly importable (and typed!)

I finally merged the site update this morning, which cross links with the github repo and also `"Step 3"` on the site now highlights which packages to use based on your selection.

Hopefully you find this more interactive and helpful.

**Comment by dabrahams** [comment]
It's your prerogative to leave out these four characters if you want of course, but FWIW that doc update wouldn't have solved the problem for me.  I have a proprietary font file that I can't upload. The code in “step 3” doesn't show me any reference to a filename; it's (still) completely non-obvious to me that digging into the "step 3" example is going to help me run the code on my font file.

On the other hand, I know there are ways to get the metrics of any font—just use a font editor and examine them—so I do that, and I look for the measurements whose names match your parameters…

Anyway, I'll stop arguing now, because I don't want to annoy you to the point where you don't want to answer [this question](https://github.com/seek-oss/capsize/discussions/60). 😉

**Comment by michaeltaranto** [comment]
Ah sorry, for clarity the readme was also updated and in the [fontMetrics](https://github.com/seek-oss/capsize#font-metrics) documentation it points you to the correct metrics extraction package for your use case.

There are many consumers who wouldn't know about the internals of fonts, and Capsize does its best to abstract that away. In particular, with the new packages meaning you dont have to know about `ascent`, `descent` etc unless you have to customise the values due to incorrect data in the font tables.

PS Im not annoyed or arguing btw 😄  just providing clarity around decisions taken so far. I did miss the discussion topic though, i'll have a look.
