### ISSUE TITLE
expose xHeight to metrics package

### ISSUE THREAD

**Issue by souporserious** [seek-oss/capsize#78]
Hello, curious if you'd be open to exposing `xHeight` for the `@capsizecss/metrics` package? I'm calculating this myself with `unpack` right now, but figured it'd be nice if it was easily available for Google Font metrics.

**Comment by michaeltaranto** [comment]
Yeah i think that shouldnt be a problem, we use it for the website and have to hack around it, so it would be cleaner if it were handled by `metrics`.

Thinking it'll be optional though as it wont be necessary for `createStyleObject` etc.

**Comment by souporserious** [comment]
Awesome! 🎉 Happy to help with a PR if you want 😁

**Comment by souporserious** [comment]
Aw yeah! Thank you! 🙏
